[package]
name = "zkhack-risczero"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "=0.19.0"}

[profile.release]
debug = 1
lto = true
opt-level = 2

[profile.release.build-override]
opt-level = 3